# Generated by Django 5.2 on 2026-05-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('partner', 'Partner'), ('customer', 'Customer')], default='customer', max_length=20),
        ),
    ]
