# Generated by Django 5.2 on 2026-03-27 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_owner_alter_booking_booking_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='selected_slots',
            field=models.ManyToManyField(blank=True, help_text='All 1-hour slots included in this booking', related_name='multi_bookings', to='bookings.slot'),
        ),
    ]
