# Generated by Django 5.2 on 2026-03-15 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='is_trial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='trial_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='trial_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan_id',
            field=models.CharField(choices=[('trial', 'Free Trial — 1 Hour'), ('starter', 'Starter — ₹999/mo'), ('pro', 'Pro — ₹2499/mo'), ('elite', 'Elite — ₹4999/mo')], default='starter', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('grace_period', 'Grace Period'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20),
        ),
    ]
