# Generated by Django 5.2 on 2026-03-16 17:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_subscription_is_trial_subscription_trial_started_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hall_limit', models.PositiveIntegerField(default=1)),
                ('has_advanced_analytics', models.BooleanField(default=False)),
                ('features', models.JSONField(default=list, help_text='List of feature strings')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'subscription_plans',
            },
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='plan_id',
        ),
        migrations.AddField(
            model_name='subscription',
            name='legacy_plan_id',
            field=models.CharField(default='starter', max_length=20),
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='subscriptions.subscriptionplan'),
        ),
    ]
