# Generated by Django 5.2 on 2026-03-19 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_subscriptionplan_remove_subscription_plan_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='default_duration_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
