# Generated by Django 5.2 on 2026-03-21 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_subscriptionplan_default_duration_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='fixed_expiry_date',
            field=models.DateTimeField(blank=True, help_text='Specific moment this plan template expires', null=True),
        ),
    ]
