# Generated by Django 5.2 on 2026-03-09 11:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyHall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(default='Tamil Nadu', max_length=100)),
                ('pincode', models.CharField(max_length=6)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('capacity_min', models.PositiveIntegerField(default=1)),
                ('base_capacity', models.PositiveIntegerField(default=10, help_text='Guest count included in base price')),
                ('capacity_max', models.PositiveIntegerField(default=50)),
                ('price_per_slot', models.DecimalField(decimal_places=2, default=1000, help_text='Legacy: fixed slot price', max_digits=10)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=500, help_text='Price per hour for dynamic duration', max_digits=10)),
                ('extra_guest_fee', models.DecimalField(decimal_places=2, default=500, help_text='Fee per guest above base_capacity', max_digits=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended'), ('subscription_expired', 'Subscription Expired')], default='pending', max_length=30)),
                ('is_active', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('trending_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('rating_avg', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('amenity_projector', models.BooleanField(default=True, help_text='Full HD Projector')),
                ('amenity_sound_system', models.BooleanField(default=True, help_text='Sony Dolby Atmos')),
                ('amenity_wifi', models.BooleanField(default=True)),
                ('amenity_decoration', models.BooleanField(default=True)),
                ('amenity_ac', models.BooleanField(default=False)),
                ('amenity_parking', models.BooleanField(default=False)),
                ('amenity_led_letters', models.BooleanField(default=False)),
                ('amenity_fog_machine', models.BooleanField(default=False)),
                ('refund_percentage_3h', models.PositiveIntegerField(default=50)),
                ('refund_percentage_2h', models.PositiveIntegerField(default=25)),
                ('refund_percentage_1h', models.PositiveIntegerField(default=0)),
                ('instant_confirmation', models.BooleanField(default=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='halls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'party_halls',
                'ordering': ['-trending_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_hours', models.PositiveIntegerField(default=1)),
                ('max_people', models.PositiveIntegerField(default=10)),
                ('inclusions', models.JSONField(default=list)),
                ('is_recommended', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='halls.partyhall')),
            ],
            options={
                'db_table': 'packages',
                'ordering': ['sort_order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='HallImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='halls.partyhall')),
            ],
            options={
                'db_table': 'party_hall_images',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='AddonService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('photography', 'Photography'), ('food', 'Food & Drinks (Buffet)'), ('decoration', 'Premium Decoration'), ('entry_effect', 'Entry Effect'), ('other', 'Other Services')], max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addon_services', to='halls.partyhall')),
            ],
            options={
                'db_table': 'addon_services',
                'ordering': ['category', 'sort_order'],
            },
        ),
    ]
