# Generated by Django 5.2 on 2026-03-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0002_partyhall_short_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='hallimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='halls/images/'),
        ),
        migrations.AlterField(
            model_name='hallimage',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
