# Generated by Django 5.2 on 2026-03-20 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0003_hallimage_image_alter_hallimage_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='partyhall',
            name='closing_time',
            field=models.TimeField(default='20:00', help_text='Hall closing time (e.g. 20:00)'),
        ),
        migrations.AddField(
            model_name='partyhall',
            name='opening_time',
            field=models.TimeField(default='09:00', help_text='Hall opening time (e.g. 09:00)'),
        ),
    ]
