# Generated by Django 5.2 on 2026-03-21 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0004_partyhall_closing_time_partyhall_opening_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='partyhall',
            name='hall_type',
            field=models.CharField(blank=True, default='', help_text='e.g. banquet, conference, outdoor', max_length=50),
        ),
        migrations.AddField(
            model_name='partyhall',
            name='max_advance_booking_days',
            field=models.PositiveIntegerField(default=90, help_text='Maximum days in advance a booking can be made'),
        ),
        migrations.AddField(
            model_name='partyhall',
            name='min_advance_booking_days',
            field=models.PositiveIntegerField(default=1, help_text='Minimum days in advance a booking can be made'),
        ),
        migrations.AddField(
            model_name='partyhall',
            name='special_instructions',
            field=models.TextField(blank=True, help_text='Noise policy, parking info, entry requirements etc.'),
        ),
        migrations.AddField(
            model_name='partyhall',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text="List of searchable tags e.g. ['Birthday', 'Corporate']"),
        ),
    ]
