# Generated by Django 5.2 on 2026-03-22 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0005_partyhall_hall_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='advance_booking_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='package',
            name='allow_extra_guests',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='package',
            name='badge_color',
            field=models.CharField(default='#7C3AED', max_length=7),
        ),
        migrations.AddField(
            model_name='package',
            name='duration_mode',
            field=models.CharField(choices=[('by_slots', 'By Slots'), ('fixed_hours', 'Fixed Hours'), ('open_ended', 'Open-Ended')], default='by_slots', max_length=20),
        ),
        migrations.AddField(
            model_name='package',
            name='fixed_hours',
            field=models.FloatField(blank=True, help_text='Exact hours covered (fixed_hours mode)', null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='guest_tiers',
            field=models.JSONField(blank=True, default=list, help_text='[{"min": 1, "max": 10, "price": 1200}, ...]'),
        ),
        migrations.AddField(
            model_name='package',
            name='max_hours',
            field=models.IntegerField(blank=True, help_text='Maximum allowed hours (open_ended mode)', null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='min_slots',
            field=models.IntegerField(blank=True, help_text='Minimum slots customer must book (by_slots mode)', null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='overtime_rate',
            field=models.IntegerField(blank=True, help_text='₹ per hour beyond fixed duration', null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='price_per_hour',
            field=models.IntegerField(blank=True, help_text='₹ per hour (open_ended mode)', null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('members_only', 'Members Only'), ('hidden', 'Hidden')], default='public', max_length=20),
        ),
    ]
