# Generated by Django 5.2 on 2026-03-28 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0006_package_advance_booking_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partyhall',
            name='extra_guest_fee_per_head',
            field=models.DecimalField(decimal_places=2, default=500, help_text='Fee (₹) per guest beyond the package max_people capacity', max_digits=8),
        ),
        migrations.AddField(
            model_name='partyhall',
            name='gap_fee_per_hour',
            field=models.DecimalField(decimal_places=2, default=200, help_text='Holding fee (₹) per hour of gap between non-consecutive slots', max_digits=8),
        ),
        migrations.AddField(
            model_name='partyhall',
            name='multi_slot_discount_pct',
            field=models.DecimalField(decimal_places=2, default=10, help_text='Discount % applied to package subtotal when >1 slot is booked (e.g. 10 = 10%)', max_digits=5),
        ),
    ]
